export const types = {
  SET_ACTIVE_SLIDE: 'SET_ACTIVE_SLIDE',
  SET_ACTIVE_TEAM: 'SET_ACTIVE_TEAM',
  SET_ACTIVE_WORK: 'SET_ACTIVE_WORK',
  SET_FOOTER_STATUS: 'SET_FOOTER_STATUS',
  SET_HEADER_STATUS: 'SET_HEADER_STATUS',
  SET_INACTIVE_SLIDE: 'SET_INACTIVE_SLIDE',
  SET_INACTIVE_TEAM: 'SET_INACTIVE_TEAM',
  SET_INACTIVE_WORK: 'SET_INACTIVE_WORK',
  SET_MENU: 'SET_MENU'
}